### ISSUE TITLE
kafka请求的支持

### ISSUE THREAD

**Issue by c625473164** [didi/rdebug#16]
下游kafka的请求可以回放到吗

**Comment by MingliangT** [comment]
只要是网络 IO 都会录制和回放。

**Comment by c625473164** [comment]
请问下如果有两次请求，两个请求都调用了某个下游，并且他们的调用参数是一样的，在回放这两个请求的时候的时候是怎么区分录制的请求是哪个呢。
因为有可能虽然参数一致，但有一个调用失败了，一个调用成功了，这里还是要区分两次下游调用

**Comment by MingliangT** [comment]
匹配的位置会记录，尽量是往后面录制的流量偏移的。

即，第一次会匹配上失败的。下一次会匹配上成功的。
