### ISSUE TITLE
How to play back the frequently changing API interface

### ISSUE THREAD

**Issue by muyu66** [didi/rdebug#5]
怎样去回放经常发生变动的API接口？
长久以来，我对这类的组件也和你们didi一样有同样的想法，但苦于下面两个问题无法实现，从而一直搁置。我看你们的文档上，并没有阐述对这个问题的解决，不知道是不是？

1、针对于 /books POST (new Book) 和 接踵而来的 /books/:bookId PATCH 这样的接口，对前端是有感知的，但是记录下来，对于后端确实无感知的。
2、API接口发生微调的接口，即只要改变一点点数据结构，即之前记录全部无效。

How to play back the API interface that changes frequently?
For a long time, I have the same idea for this type of component as you did with didi, but I have been stuck with the following two problems. I see your document, and did not explain the solution to this problem, I don't know if it is?

1. The interface for /books POST (new Book) and the incoming /books/:bookId PATCH is perceptual to the front end, but it is recorded and is not perceived by the back end.
2. The interface of the API interface is fine-tuned, that is, as long as the data structure is changed a little, that is, all the previous records are invalid.

**Comment by MingliangT** [comment]
这涉及流量的匹配，目前有两种匹配算法，一个是块匹配，一个是余弦相似度匹配。你说的微调，是没有影响的。

具体看一下 wik https://github.com/didi/rdebug/wiki/%E8%AF%B7%E6%B1%82%E5%8C%B9%E9%85%8D
